script: npm run deploy
language: node_js
node_js:
- '5'
env:
  global:
  - GH_REF: github.com/cuffs/cuffs.github.io.git
  - secure: dZg9DOlMTXw+DfMvMpA+KO2pSM8edVR6Fs1u0VMio2xgvTl65+WjugULMARVJOz31V2tXFTVdISNTd6mD6ZL9j0YHCfqmOub0Vb4eErR6DPbThPtcw0cOLJo7CcKfut+i8B0EH4miL5uRtMN0RfDNIkmYDsBAvAYTpTWlGtny0s2kp5QSadKeIBV6mstjFMbr6kcZAq4Uk8rkiPT8V5Z5NloEJxulMyrltljskWD3S0T1/598q+zRf/D3Vdf3AmqRcdeiFub/1m4uo4w8+6odv/jXGFMzI1F5mxCMdNCox1AU5tDFXNksMdYBSNzTtDD3zKu15Drx0S7ovxEXuKb06zY8qWSD4/tF/2L1OzyyCgJydyJrvz6x4//roOEesh/a7dPLtQ9BQOkhysni7mb9I3fHUBCouF/KIRZNfJIwLVXISXdZ6KK7axndFPb/Wh/tVNPgf+Kjxht97dVMXngpLRyOPo6Q5UYwICXJKOeCIUk7IwLZ9JqRILpNda0OLxo0lWqqenHkQMhwpi+yPoB4DhaN7OmLl/HdF6eFHx6Bm7I5zL2vN84RMl7FPMcH25ZiTzWwCeNojT0M9hHGsC4/nYTdvufpzvL5n2x28AjABWU6xWJpLXUeVt0NNZAiytJYYwC7pp3zFfgFvsh8FmQ8zrj3vH0ZC9ZUwGK+CxJUq0=
